#  ***************************************************************************
#  Copyright 2017 - 2023, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        aadpodidbinding: {{ .Values.global.podidentity }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: "{{ .Values.configEnv.sdmsPrefix }}/status"
              port: 5000
              httpHeaders:
                - name: X-Api-Key
                  value: ""
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: "{{ .Values.configEnv.sdmsPrefix }}/status"
              port: 5000
              httpHeaders:
                - name: X-Api-Key
                  value: ""
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 60  
          ports:
            - protocol: TCP
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-properties"