#  ***************************************************************************
#  Copyright 2017 - 2023, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************

include:
  # global
  - local: "app/sdms-v4/devops/osdu/global/gitlab.yml"

  # containerize
  # osdu
  - local: "app/sdms-v4/devops/osdu/containerize/osdu.yml"
  
  # scanners
  # cspell
  - local: "app/sdms-v4/devops/osdu/scanners/cspell-node.yml"

  # markdownlint
  - local: "app/sdms-v4/devops/osdu/scanners/markdownlint-node.yml"
  
  # lint
  - local: "app/sdms-v4/devops/osdu/scanners/lint-node.yml"
  
  # prettier
  - local: "app/sdms-v4/devops/osdu/scanners/prettier-node.yml"
  
  # scan for secrets
  - local: "app/sdms-v4/devops/osdu/scanners/scan-for-secrets-node.yml"

  # vulnerability Scan
  - local: "app/sdms-v4/devops/osdu/scanners/gitlab-ultimate.yml"

  # deploy
  # azure
  - local: "app/sdms-v4/devops/osdu/cloud-providers/azure.yml"
  # deploy
  # aws
  - local: "app/sdms-v4/devops/osdu/cloud-providers/aws.yml"
