include:
  # PIPELINE LOGIC
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: v0.29.5

  # SCANNERS
  # ultimate
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/scanners/gitlab-ultimate.yml

  # virus scan
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/virus-scan.yml"
    ref: v0.29.5

  # CLOUD PROVIDERS
  # aws
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/cloud-providers/aws-global.yml

  # azure
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/cloud-providers/azure.yml

  # gc
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/cloud-providers/gc-global.yml

  # core
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/core-global.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/cloud-providers/core-global.yml

  # ibm
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"
    ref: v0.29.5

  # overwrite logic
  - local: devops/osdu/cloud-providers/ibm.yml

  # SERVICES (APPS)
  # filemetadata
  - local: app/filemetadata/.gitlab-ci.yml

  # sdms
  - local: app/sdms/.gitlab-ci.yml

  # sdms v4
  - local: app/sdms-v4/.gitlab-ci.yml
