# cSpell:words buildx

variables:
  #aws variables
  AWS_BUILD_SUBDIR: src/cloud/providers/aws/build-aws
  AWS_CHART_SUBDIR: app/sdms-v4/devops/aws/chart
  AWS_SERVICE_GATEWAY: osdu-services/osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: TF
  AWS_RUNTIME_DOCKERFILE_PATH: src/cloud/providers/aws/build-aws/runtime.Dockerfile
  # skipping tests here. Using a local file to run tests
  AWS_SKIP_TESTS: "true"
  SDMS_V4_SERVICE_NAME: seismic-ddms-v4

sdms-v4_aws_containerize:
  extends:
    - aws-containerize
  variables:
    LOCAL_IMAGE_TAG: ${CI_REGISTRY_IMAGE}/os-seismic-store-v4-aws:${CI_COMMIT_SHA}
    AWS_IMAGE_TAG_BASE: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/os-seismic-store-v4 
  needs: ['sdms-v4_containerize']
  before_script:
    - !reference [.aws, before_script]
    - cd app/$SDMS_V4_SERVICE
  script:    
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - $(aws ecr get-login --no-include-email --region $AWS_ECR_REGION)
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --pull --push -f $AWS_RUNTIME_DOCKERFILE_PATH -t $LOCAL_IMAGE_TAG -t $AWS_IMAGE_TAG_BASE:$CI_COMMIT_SHA -t $AWS_IMAGE_TAG_BASE:latest .;

  only: null
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/' && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_TAG && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $AWS == '1'
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
      when: on_success

sdms-v4_aws-update-tf:
  extends: 
    - aws-update-tf
  variables:
    AWS_EKS_DEPLOYMENT_NAME: os-seismic-store-v4
    AWS_SERVICE_NAMESPACE_SUFFIX: seismic-store-v4
    AWS_IMAGE_TAG_BASE: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/os-seismic-store-v4 
  needs: ['sdms-v4_aws_containerize']
  before_script:
    - !reference [.aws_variables, before_script]
    - !reference [.aws, before_script]
    - cd app/$SDMS_V4_SERVICE
  script:
    - export KUBECONFIG=/tmp/kubeconfig-${RANDOM}.yaml
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME --role-arn $EKS_CLUSTER_MGMT_ROLE
    - chmod 600 $KUBECONFIG
    - export CONTAINER_IMAGE=`kubectl -n ${AWS_SERVICE_NAMESPACE}-${AWS_SERVICE_NAMESPACE_SUFFIX} get deployment/${AWS_EKS_DEPLOYMENT_NAME} -o jsonpath='{.spec.template.spec.containers[0].name}'`
    - kubectl -n ${AWS_SERVICE_NAMESPACE}-${AWS_SERVICE_NAMESPACE_SUFFIX} set image deployment/${AWS_EKS_DEPLOYMENT_NAME} $CONTAINER_IMAGE=$AWS_IMAGE_TAG_BASE:$CI_COMMIT_SHA
    - kubectl -n ${AWS_SERVICE_NAMESPACE}-${AWS_SERVICE_NAMESPACE_SUFFIX} rollout restart deployment/${AWS_EKS_DEPLOYMENT_NAME}
    - kubectl -n ${AWS_SERVICE_NAMESPACE}-${AWS_SERVICE_NAMESPACE_SUFFIX} rollout status -w deployment/${AWS_EKS_DEPLOYMENT_NAME} --timeout=300s
  only: null
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/' && $AWS == '1' && $AWS_SKIP_DEPLOY != 'true' && $AWS_DEPLOY_TARGET == 'TF'
      when: on_success
    - if: $CI_COMMIT_TAG && $AWS == '1' && $AWS_SKIP_DEPLOY != 'true' && $AWS_DEPLOY_TARGET == 'TF'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $AWS == '1' && $AWS_SKIP_DEPLOY != 'true' && $AWS_DEPLOY_TARGET == 'TF'
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $AWS == '1' && $AWS_SKIP_DEPLOY != 'true' && $AWS_DEPLOY_TARGET == 'TF'
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
      when: on_success

sdms-v4_aws_test:
  extends:
    - .aws
    - .aws_common_variables
    - .aws_variables
  stage: integration
  image: $CI_REGISTRY/osdu/platform/deployment-and-operations/base-containers-aws/aws-node/aws-node:v1.0-node18
  needs: ['sdms-v4_aws-update-tf']
  before_script:
    - !reference [.aws_variables, before_script]
    - !reference [.aws, before_script]
    - cd app/$SDMS_V4_SERVICE 
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python3 -m pip install -r devops/aws/requirements.txt
    - svctoken=$(python3 ../../devops/scripts/aws_jwt_client.py)
    - npm install
  script:
    - chmod +x ./tests/e2e/run.sh
    - ./tests/e2e/run.sh --osdu-url=$AWS_BASE_URL --access-token=$svctoken --partition='osdu' --acl-owners='data.default.owners@osdu.example.com' --acl-viewers='data.default.viewers@osdu.example.com'
  artifacts:
    when: always
    paths:
      - app/$SDMS_V4_SERVICE/tests
    expire_in: 14 days
  only: null
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/' && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_TAG && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $AWS == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $AWS == '1'
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
      when: on_success
