include:

  # global
  - local: "app/filemetadata/devops/osdu/global/gitlab.yml"

  # containerize
  - local: "app/filemetadata/devops/osdu/containerize/osdu.yml"

  # scanners
  # scan for secrets
  - local: "app/filemetadata/devops/osdu/scanners/scan-for-secrets-python.yml"

  # vulnerability Scan
  - local: "app/filemetadata/devops/osdu/scanners/gitlab-ultimate.yml"

  # deploy
  # azure
  - local: "app/filemetadata/devops/osdu/cloud-providers/azure.yml"
