#  ***************************************************************************
#  Copyright 2017 - 2024, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************

include:

  # VARIABLES
  - local: "app/filemetadata/devops/osdu/variables/variables.yml"

  # PREPARE
  - local: "app/filemetadata/devops/osdu/prepare/prepare.yml"

  # BUILD
  - local: "app/filemetadata/devops/osdu/build/compile-and-unit-test.yml"

  # CONTAINERIZE
  - local: "app/filemetadata/devops/osdu/containerize/containerize.yml"

  # SCANNERS
  # fossa
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-python.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $FOSSA_API_KEY
      - if: $CI_COMMIT_TAG && $FOSSA_API_KEY
      - if: $CI_COMMIT_BRANCH =~ 'trusted-.+' && $FOSSA_API_KEY
      - if: $CI_COMMIT_REF_PROTECTED && $FOSSA_API_KEY
      - if: $FOSSA_API_KEY
        changes:
          - app/filemetadata/**/*
    ref: v0.29.5
    # overwrite logic
  - local: "app/filemetadata/devops/osdu/scanners/fossa-python.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $FOSSA_API_KEY
      - if: $CI_COMMIT_TAG && $FOSSA_API_KEY
      - if: $CI_COMMIT_BRANCH =~ 'trusted-.+' && $FOSSA_API_KEY
      - if: $CI_COMMIT_REF_PROTECTED && $FOSSA_API_KEY
      - if: $FOSSA_API_KEY
        changes:
          - app/filemetadata/**/*

  # cspell
  - local: "app/filemetadata/devops/osdu/scanners/cspell-python.yml"

  # markdownlint
  - local: "app/filemetadata/devops/osdu/scanners/markdownlint-python.yml"

  # ultimate
  - local: "app/filemetadata/devops/osdu/scanners/gitlab-ultimate.yml"

  # CLOUD PROVIDERS
  # azure
  - local: "app/filemetadata/devops/osdu/cloud-providers/azure.yml"
