#  ***************************************************************************
#  Copyright 2017 - 2024, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************

sdms-v4_containerize:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags: ["osdu-medium"]
  stage: containerize
  variables:
    SHA_IMAGE: ${SDMS_V4_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDMS_V4_PROJECT_NAME}:latest
  before_script:
    - cd app/$SDMS_V4_SERVICE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $SDMS_V4_UTEST_RUNTIME_IMAGE --file docker/runtime.Dockerfile  .
    - docker tag $SDMS_V4_UTEST_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker tag $SDMS_V4_UTEST_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$LATEST_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
      when: always

sdms-v4_ms_sdms-sync-v3v4_containerize:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags: ["osdu-medium"]
  stage: containerize
  variables:
    SHA_IMAGE: ${SDMS_V4_MS_SDMS_SYNC_V3V4_RUNTIME_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDMS_V4_MS_SDMS_SYNC_V3V4_RUNTIME_IMAGE}:latest
  before_script:
    - cd app/$SDMS_V4_SERVICE/microservices
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd sdms-sync-v3v4
    - docker build -t $SDMS_V4_MS_SDMS_SYNC_V3V4_RUNTIME_IMAGE --file Dockerfile  .
    - docker tag $SDMS_V4_MS_SDMS_SYNC_V3V4_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker tag $SDMS_V4_MS_SDMS_SYNC_V3V4_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$LATEST_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
      when: always
