sdms_cspell:
  image: node
  stage: scan
  needs: ['sdms_compile-and-unit-test']
  before_script:
    - cd app/$SDMS_SERVICE
  script:
    - npm install -g typescript
    - npm install -g cspell
    - cspell "**" --quiet --gitignore --config=../../cspell.json --show-suggestions --reporter default > cspell_report.txt
  artifacts:
    paths:
      - app/$SDMS_SERVICE/cspell_report.txt
    when: always
    expire_in: 2 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: never
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - devops/**/*
        - app/sdms/**/*
      when: always
