sdms_scan-for-secrets:
  image: python
  tags: ["osdu-small"]
  stage: scan
  needs:
    - job: sdms_compile-and-unit-test
      artifacts: false
  script:
    - pip install detect-secrets
    - cd app/$SDMS_SERVICE
    - detect-secrets-hook --exclude-files npm-shrinkwrap.json --exclude-files package.json --exclude-files docs/api/openapi.yaml --exclude-files devops/osdu/scanners/scan-for-secrets-node.yml --baseline devops/config/detect_secrets/.secrets.baseline $(git ls-files)
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - merge_requests
