.fossa-check-notice:
  script:
    # Check to see if a newer commit exists for the pipeline's branch, and if it does, use that NOTICE instead of this one's
    - |
      if [ "$CI_COMMIT_BRANCH" != "" ]; then
        colorCmd="\e[32;1m"
        colorReset="\e[0m"
        function echoCmd() {
          echo -e "${colorCmd}>" "$@" "${colorReset}"
        }
        echoCmd git fetch
        git fetch
        echoCmd git diff --name-only HEAD origin/$CI_COMMIT_BRANCH
        branchDiffs="$(git diff --name-only HEAD origin/$CI_COMMIT_BRANCH)"
        echo $branchDiffs
        echo "--------------------"
        if [ "$branchDiffs" == "NOTICE" ]; then
          echo "The branch associated with this pipeline ($CI_COMMIT_BRANCH) has been changed, but the only changes are the NOTICE file"
          echo "I will use the NOTICE file from origin/$CI_COMMIT_BRANCH ($(git rev-parse --short origin/$CI_COMMIT_BRANCH)) as the basis for comparison"
          echoCmd git checkout origin/$CI_COMMIT_BRANCH -- NOTICE
          git checkout origin/$CI_COMMIT_BRANCH -- NOTICE
        elif [ "$branchDiffs" == "" ]; then
          echo "The branch associated with this pipeline ($CI_COMMIT_BRANCH) has not been changed since the commit that spawned this pipeline"
          echo "I will use the NOTICE file from the pipeline's commit ($CI_COMMIT_SHORT_SHA) as the basis for comparison"
        else
          echo "The branch associated with this pipeline ($CI_COMMIT_BRANCH) has been changed, but the changes include more than just the NOTICE file"
          echo "I will use the NOTICE file from the pipeline's commit ($CI_COMMIT_SHORT_SHA) as the basis for comparison"
        fi
      fi
    # Use a cached NOTICE if available, otherwise use a generated one
    - |
      if [ -e ${NOTICE_PATH_OUTPUT}/cached-NOTICE ]; then
        fossaGeneratedNotice=${CACHED_NOTICE_PATH}/cached-NOTICE;
      elif [ -e ${NOTICE_PATH_OUTPUT}/generated-clean-NOTICE ]; then
        fossaGeneratedNotice=${NOTICE_PATH_OUTPUT}/generated-clean-NOTICE
      else
        echo "Couldn't find either a cached-NOTICE or generated-clean-NOTICE in the fossa-output/ directory"
        echo
        echo "At least one of these should have been generated by a previous job stage (fossa-analyze) and stored"
        echo "as an artifact. Something must be wrong in the CI setup"
        exit 1
      fi
      echo "Comparing with $fossaGeneratedNotice"
    # If the comparison finds differences, let the user know what to do next
    - |
      if ! fossa-compare-notices NOTICE $fossaGeneratedNotice; then
        echo --------------------------------------------------------------------------------
        echo "There are differences in the NOTICE file"
        echo "Please review these differences, and if they look appropriate based on your"
        echo "changes, update the committed NOTICE file"
        echo "--------------------"
        if [[ "$CI_COMMIT_BRANCH" =~ ^trusted ]]; then
          MAIN_BRANCH=$(echo "$CI_COMMIT_BRANCH" | sed 's/^trusted-//')
          echo "Since you are running this on a trusted branch, you will need to update both the main branch"
          echo "and the trusted branch, push both, and re-run the entire pipeline"
          echo "Here are some commands to do that:"
          echo "$ wget -O NOTICE '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/${fossaGeneratedNotice}?inline=false'"
          echo "$ git add NOTICE"
          echo "$ git commit -m 'Updating NOTICE'"
          echo "$ git branch -f $CI_COMMIT_BRANCH $MAIN_BRANCH"
          echo "$ git push -u origin $CI_COMMIT_BRANCH $MAIN_BRANCH"
          echo "This will automatically reinvoke the pipeline"
        else
          echo "If you make changes to the NOTICE file (and only the NOTICE file), you can"
          echo "re-run this single stage of the pipeline alone rather than the whole pipeline"
          echo "One way to achieve this:"
          echo "$ wget -O NOTICE '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/${fossaGeneratedNotice}?inline=false'"
          echo "$ git add NOTICE"
          echo "$ git commit -m 'Updating NOTICE'"
          echo "$ git push -o ci.skip"
          echo "Then retry this job. The latest pipeline will show as skipped, but this one will show as passed"
        fi
        exit 1
      else
        echo "No significant differences found between the committed NOTICE file and the generated one"
      fi
