dependency_scanning:
  extends: .seismic-dms-service_ultimate-scanner-config
  rules:
    - when: never

sast:
  extends: .seismic-dms-service_ultimate-scanner-config
  rules:
    - when: never

secret_detection:
  extends:
    - .seismic-dms-service_ultimate-scanner-config
    - .secret-analyzer
  rules:
    - when: never

nodejs-scan-sast:
  rules:
    - when: never

semgrep-sast:
  rules:
    - when: never

gemnasium-maven-dependency_scanning:
  rules:
    - when: never

gemnasium-python-dependency_scanning:
  dependencies: []
  rules:
    - when: never

gemnasium-dependency_scanning:
  rules:
    - when: never

.seismic-dms-service_ultimate-scanner-config:
  extends: .ultimate-scanner-config
  needs: []