global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  tier: ""
  autoscaling: true

data:
  # Configmap
  logLevel: "ERROR"
  port: "5000"
  partitionHost: "http://partition"
  storageHost: "http://storage"
  legalHost: "http://legal"
  entitlementsHost: "http://entitlements"
  redisSdmsHost: ""
  redisSdmsPort: "6379"
  redisSdmsTlsDisabled: true
  serviceEnv: "dev"
  # Deployment
  requestsCpu: "5m"
  requestsMemory: "150Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "seismic-store"
  imagePullPolicy: "IfNotPresent"
  redisImage: "docker.io/library/redis:7.2-alpine"
  image: ""

conf:
  configmap: "seismic-store-config"
  appName: "seismic-store"
  # onprem configuration
  database: "seismic-store-db-secret"
  keycloak: "seismic-store-keycloak-secret"
  minio: "seismic-store-minio-secret"
  sdmsRedisSecretName: "seismic-store-redis-secret" # pragma: allowlist secret
  replicas: 1

istio:
  proxyCPU: "6m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue" #Could be AverageValue or Value
  targetValue: 16 #8 rps
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 12
  tokensPerFill: 12
  fillInterval: "1s"
