variables:
  CIMPL_INT_TEST_TYPE: python

sdms_cimpl-dev-deploy:
  extends:
    - cimpl-dev-deploy
    - .cimpl-dev-variables
  needs:
    - 'sdms_cimpl-containerize-gitlab'
    - 'sdms_cimpl-helm-charts-gitlab'
  variables:
    CIMPL_SERVICE: seismic-store
    CIMPL_HELM_DEPLOYMENT_DIR: "app/sdms/devops/core-plus/deploy"
    CIMPL_HELM_TIMEOUT: "--timeout=1200s"
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$CIMPL_STACK == "1" && $DEV == "1"'
      when: on_success

sdms_cimpl-dev-test-python:
  environment:
    name: cimpl_dev
  extends:
    - cimpl-dev-test-python
    - .cimpl-dev-variables
  stage: integration
  tags: ["osdu-medium"]
  image: node:22-bookworm
  needs: ["sdms_cimpl-dev-deploy"]
  variables:
    CIMPL_SEISTORE_LEGALTAG01: osdu-demo-legaltag
    CIMPL_SEISTORE_LEGALTAG02: osdu-osdu-demo-legaltag
    CIMPL_SEISTORE_ADMIN_EMAIL: integration-tester@service.local
  allow_failure: true
  retry: 1
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -yq jq curl
    - >
      CIMPL_ID_TOKEN=$(curl --location --silent --request POST "${TEST_OPENID_PROVIDER_URL}/protocol/openid-connect/token"
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data-urlencode grant_type=client_credentials
      --data-urlencode scope=openid
      --data-urlencode client_id=${TEST_OPENID_PROVIDER_CLIENT_ID}
      --data-urlencode client_secret=${TEST_OPENID_PROVIDER_CLIENT_SECRET} | jq -r .id_token)
    - mkdir -pv "cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl"
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - >
      ./tests/e2e/run_e2e_tests.sh
      --seistore-svc-url="${HOST}${CIMPL_SDMS_PREFIX}"
      --seistore-svc-api-key="NA"
      --user-idtoken="$CIMPL_ID_TOKEN"
      --tenant="${CIMPL_TENANT}"
      --admin-email="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --datapartition="${DEFAULT_DATA_PARTITION_ID_TENANT1}"
      --legaltag01="${CIMPL_SEISTORE_LEGALTAG01}"
      --legaltag02="${CIMPL_SEISTORE_LEGALTAG02}"
      --VCS-Provider="${ISGITLAB}"
      --hostname="${HOST}"
      --domain_name="${DOMAIN:-group}"
      --entitlements_user="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --allure-dir="cimpl/allure-results"
  after_script:
    - mkdir -pv "$CI_PROJECT_DIR/tests/cimpl"
    - cp -avr "app/$SDMS_SERVICE/cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl/"
  artifacts:
    when: always
    paths:
      - tests/cimpl/allure-results/
    expire_in: 1 month
  rules:
    - if: '$DISABLE_INTEGRATION_TEST == "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$CIMPL_STACK == "1" && $CIMPL_INT_TEST_TYPE == "python" && $DEV == "1"'
      when: on_success

sdms_cimpl-dev-backup-deploy:
  extends:
    - cimpl-dev-backup-deploy
    - .cimpl-dev-backup-variables
  needs:
    - 'sdms_cimpl-containerize-gitlab'
    - 'sdms_cimpl-helm-charts-gitlab'
  variables:
    CIMPL_SERVICE: seismic-store
    CIMPL_HELM_DEPLOYMENT_DIR: "app/sdms/devops/core-plus/deploy"
    CIMPL_HELM_TIMEOUT: "--timeout=1200s"
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$CIMPL_STACK == "1" && $DEV_BACKUP == "1"'
      when: on_success

sdms_cimpl-dev-backup-test-python:
  environment:
    name: cimpl_dev
  extends:
    - cimpl-dev-backup-test-python
    - .cimpl-dev-backup-variables
  stage: integration
  tags: ["osdu-medium"]
  image: node:22-bookworm
  needs: ["sdms_cimpl-dev-deploy"]
  variables:
    CIMPL_SEISTORE_LEGALTAG01: osdu-demo-legaltag
    CIMPL_SEISTORE_LEGALTAG02: osdu-osdu-demo-legaltag
    CIMPL_SEISTORE_ADMIN_EMAIL: integration-tester@service.local
  allow_failure: true
  retry: 1
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -yq jq curl
    - >
      CIMPL_ID_TOKEN=$(curl --location --silent --request POST "${TEST_OPENID_PROVIDER_URL}/protocol/openid-connect/token"
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data-urlencode grant_type=client_credentials
      --data-urlencode scope=openid
      --data-urlencode client_id=${TEST_OPENID_PROVIDER_CLIENT_ID}
      --data-urlencode client_secret=${TEST_OPENID_PROVIDER_CLIENT_SECRET} | jq -r .id_token)
    - mkdir -pv "cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl"
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - >
      ./tests/e2e/run_e2e_tests.sh
      --seistore-svc-url="${HOST}${CIMPL_SDMS_PREFIX}"
      --seistore-svc-api-key="NA"
      --user-idtoken="$CIMPL_ID_TOKEN"
      --tenant="${CIMPL_TENANT}"
      --admin-email="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --datapartition="${DEFAULT_DATA_PARTITION_ID_TENANT1}"
      --legaltag01="${CIMPL_SEISTORE_LEGALTAG01}"
      --legaltag02="${CIMPL_SEISTORE_LEGALTAG02}"
      --VCS-Provider="${ISGITLAB}"
      --hostname="${HOST}"
      --domain_name="${DOMAIN:-group}"
      --entitlements_user="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --allure-dir="cimpl/allure-results"
  after_script:
    - mkdir -pv "$CI_PROJECT_DIR/tests/cimpl"
    - cp -avr "app/$SDMS_SERVICE/cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl/"
  artifacts:
    when: always
    paths:
      - tests/cimpl/allure-results/
    expire_in: 1 month
  rules:
    - if: '$DISABLE_INTEGRATION_TEST == "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$CIMPL_STACK == "1" && $CIMPL_INT_TEST_TYPE == "python" && $DEV_BACKUP == "1"'
      when: on_success

sdms_cimpl-prod-deploy:
  extends:
    - cimpl-prod-deploy
    - .cimpl-prod-variables
  needs:
    - 'sdms_cimpl-containerize-gitlab'
    - 'sdms_cimpl-helm-charts-gitlab'
  variables:
    CIMPL_SERVICE: seismic-store
    CIMPL_HELM_DEPLOYMENT_DIR: "app/sdms/devops/core-plus/deploy"
    CIMPL_HELM_TIMEOUT: "--timeout=1200s"
  rules:
    - if: '$CIMPL_STACK == "1" && $CI_COMMIT_BRANCH =~ /^release/'
      when: on_success
    - if: '$CIMPL_STACK == "1" && $CI_COMMIT_TAG'
      when: on_success

sdms_cimpl-prod-test-python:
  environment:
    name: cimpl_prod
  extends:
    - cimpl-prod-test-python
    - .cimpl-prod-variables
  stage: integration
  tags: ["osdu-medium"]
  image: node:22-bookworm
  needs: ["sdms_cimpl-prod-deploy"]
  variables:
    CIMPL_SEISTORE_LEGALTAG01: osdu-demo-legaltag
    CIMPL_SEISTORE_LEGALTAG02: osdu-osdu-demo-legaltag
    CIMPL_SEISTORE_ADMIN_EMAIL: integration-tester@service.local
  allow_failure: true
  retry: 1
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -yq jq curl
    - >
      CIMPL_ID_TOKEN=$(curl --location --silent --request POST "${TEST_OPENID_PROVIDER_URL}/protocol/openid-connect/token"
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data-urlencode grant_type=client_credentials
      --data-urlencode scope=openid
      --data-urlencode client_id=${TEST_OPENID_PROVIDER_CLIENT_ID}
      --data-urlencode client_secret=${TEST_OPENID_PROVIDER_CLIENT_SECRET} | jq -r .id_token)
    - mkdir -pv "cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl"
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - >
      ./tests/e2e/run_e2e_tests.sh
      --seistore-svc-url="${HOST}${CIMPL_SDMS_PREFIX}"
      --seistore-svc-api-key="NA"
      --user-idtoken="$CIMPL_ID_TOKEN"
      --tenant="${CIMPL_TENANT}"
      --admin-email="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --datapartition="${DEFAULT_DATA_PARTITION_ID_TENANT1}"
      --legaltag01="${CIMPL_SEISTORE_LEGALTAG01}"
      --legaltag02="${CIMPL_SEISTORE_LEGALTAG02}"
      --VCS-Provider="${ISGITLAB}"
      --hostname="${HOST}"
      --domain_name="${DOMAIN:-group}"
      --entitlements_user="${CIMPL_SEISTORE_ADMIN_EMAIL}"
      --allure-dir="cimpl/allure-results"
  after_script:
    - mkdir -pv "$CI_PROJECT_DIR/tests/cimpl"
    - cp -avr "app/$SDMS_SERVICE/cimpl/allure-results" "$CI_PROJECT_DIR/tests/cimpl/"
  artifacts:
    when: always
    paths:
      - tests/cimpl/allure-results/
    expire_in: 1 month
  rules:
    - if: '$CIMPL_INT_TEST_TYPE == "python" && $CIMPL_STACK == "1" && $CI_COMMIT_BRANCH =~ /^release/'
      when: on_success
    - if: '$CIMPL_INT_TEST_TYPE == "python" && $CIMPL_STACK == "1" && $CI_COMMIT_TAG'
      when: on_success