sdms_core-deploy:
  allow_failure: true
  extends:
    - core-deploy
  needs: 
    - 'sdms_core-containerize-gitlab'
    - 'sdms_core-helm-charts-gitlab'
  variables:
    CORE_SA_EMAIL: $CORE_SA_GKE_EMAIL
    CORE_HELM_DEPLOYMENT_SERVICE: seismic-store-deploy
    CORE_HELM_DEPLOYMENT_DIR: "app/sdms/devops/core-plus/deploy"
    CORE_SERVICE: seismic-store
    CORE_HELM_TIMEOUT: "--timeout=1200s"
  retry: 1
  script:
    - !reference [.core_obtain_credentials, script]
    - !reference [.core_set_image_name, script]
    - !reference [.core_common_config, script]
    - >
      helm upgrade $CORE_SERVICE-deploy oci://$CI_REGISTRY_IMAGE/core-helm/$CORE_HELM_PACKAGE_NAME
      --version $CORE_HELM_PACKAGE_VERSION-$CORE_HELM_TAG
      --install
      --create-namespace
      --namespace=$CORE_HELM_NAMESPACE
      --wait
      --history-max=3
      --set global.onPremEnabled=true
      --set global.domain=$CORE_DOMAIN
      --set global.dataPartitionId=$CORE_TENANT
      --set data.serviceAccountName=$CORE_SERVICE
      --set data.bootstrapServiceAccountName=$CORE_BOOTSTRAP_SA
      --set data.cronJobServiceAccountName=$CORE_BOOTSTRAP_SA
      --set data.logLevel=INFO
      --set data.bucketPrefix="refi"
      --set data.groupId=$GROUP_ID
      --set data.sharedTenantName=$CORE_TENANT
      --set data.googleCloudProject=$CORE_PROJECT
      --set data.subscriberPrivateKeyId=$CORE_SUBSCRIBER_PRIVATE_KEY_ID
      $CORE_HELM_SETS
      $CORE_HELM_TIMEOUT
    - !reference [.core_verify_deploy, script]
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CORE == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $CORE == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CORE == '1'
      changes:
        - devops/**/*
        - app/sdms/**/*
      when: on_success

sdms_core-test-python:
  environment:
    name: Core
  extends:
    - core-test-python
  stage: integration
  tags: ["osdu-small"]
  image: node
  needs: ["sdms_core-deploy"]
  variables:
    CORE_SEISTORE_LEGALTAG01: osdu-demo-legaltag
    CORE_SEISTORE_LEGALTAG02: osdu-osdu-demo-legaltag
    CORE_SEISTORE_ADMIN_EMAIL: integration-tester@service.local
  allow_failure: true
  retry: 1
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -yq jq curl
    - >
      CORE_ID_TOKEN=$(curl --location --silent --request POST "${TEST_OPENID_PROVIDER_URL}/protocol/openid-connect/token"
      --header "data-partition-id: ${DEFAULT_DATA_PARTITION_ID_TENANT1}"
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data-urlencode grant_type=client_credentials
      --data-urlencode scope=openid
      --data-urlencode client_id=${TEST_OPENID_PROVIDER_CLIENT_ID}
      --data-urlencode client_secret=${TEST_OPENID_PROVIDER_CLIENT_SECRET} | jq -r .id_token)
    - npm install -g newman
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - >
      ./tests/e2e/run_e2e_tests.sh
      --seistore-svc-url="${HOST}${CORE_SDMS_PREFIX}"
      --seistore-svc-api-key="NA"
      --user-idtoken="$CORE_ID_TOKEN"
      --tenant="${CORE_TENANT}"
      --admin-email="${CORE_SEISTORE_ADMIN_EMAIL}"
      --datapartition="${DEFAULT_DATA_PARTITION_ID_TENANT1}"
      --legaltag01="${CORE_SEISTORE_LEGALTAG01}"
      --legaltag02="${CORE_SEISTORE_LEGALTAG02}"
      --VCS-Provider="${ISGITLAB}"

  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CORE == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $CORE == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CORE == '1'
      changes:
        - devops/**/*
        - app/sdms/**/*
      when: on_success
