sdms_gc-dev2-deploy:
  extends:
    - gc-dev2-deploy
  needs: 
    - 'sdms_gc-containerize-gitlab'
    - 'sdms_gc-helm-charts-release-gitlab'
  variables:
    GC_HELM_DEPLOYMENT_SERVICE: seismic-store-deploy
    GC_HELM_DEPLOYMENT_DIR: "app/sdms/devops/gc/deploy"
    GC_SERVICE: seismic-store
    GC_HELM_TIMEOUT: "--timeout=1200s"
  script:
    - !reference [.gc_obtain_credentials, script]
    - !reference [.gc_common_config, script]
    - !reference [.gc_define_version, script]
    - !reference [.gc_set_image_name, script]
    - >
      helm upgrade $GC_HELM_DEPLOYMENT_SERVICE oci://$CI_REGISTRY_IMAGE/gc-helm/gc-$GC_SERVICE-deploy
      --version $VERSION
      --install
      --create-namespace
      --namespace=$GC_HELM_NAMESPACE
      --wait
      --history-max=3
      --set data.imagePullPolicy=Always
      --set data.serviceAccountName=$GC_SERVICE
      --set global.domain=$GC_DOMAIN
      --set data.serviceCloudProject=$GC_PROJECT
      $GC_HELM_SETS
      $GC_HELM_TIMEOUT
    - !reference [.gc_verify_deploy, script]
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: on_success
    - if: $CI_COMMIT_TAG && $GC == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $GC == '1'
      when: never

sdms_gc-dev2-test:
  extends:
    - gc-dev2-test
  image: node
  needs: ['sdms_gc-dev2-deploy']
  allow_failure: true
  variables:
    GOOGLE_CREDENTIALS: $GC_R3_INTEGRATION_TESTER
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -y python3
    - apt-get install -y python3-pip
    - pip install google --break-system-packages
    - pip install google-auth --break-system-packages
    - pip install google-api-python-client --break-system-packages
    - pip install google-auth-httplib2 --break-system-packages
    - pip install google-auth-oauthlib --break-system-packages
    - export GC_AUDIENCE=$INTEGRATION_TEST_AUDIENCE
    - export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_CREDENTIALS
    - svctoken=$(python3 ../../devops/scripts/gc_jwt_client.py)
    - echo $svctoken > /dev/null
    - npm install -g newman
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - ./tests/e2e/run_e2e_tests.sh --seistore-svc-url="https://${GC_UNIT_HOSTNAME}${GC_SDMS_PREFIX}" --seistore-svc-api-key="NA" --user-idtoken="$GC_INTEGRATION_TESTER" --tenant="${GC_TENANT}" --admin-email="${GC_SEISTORE_ADMIN_EMAIL}" --datapartition="${DATA_PARTITION_ID}" --legaltag01="${GC_SEISTORE_LEGALTAG01}" --legaltag02="${GC_SEISTORE_LEGALTAG02}" --VCS-Provider="${ISGITLAB}"
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: on_success
    - if: $CI_COMMIT_TAG && $GC == '1'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $GC == '1'
      when: never
