sdms_gc-preship-deploy:
  extends:
    - gc-preship-deploy
  needs: 
    - 'sdms_gc-dev2-deploy'
  variables:
    GC_HELM_DEPLOYMENT_SERVICE: seismic-store-deploy
    GC_HELM_DEPLOYMENT_DIR: "app/sdms/devops/gc/deploy"
    GC_SERVICE: seismic-store
    GC_HELM_TIMEOUT: "--timeout=1200s"
  script:
    - !reference [.gc_obtain_credentials, script]
    - !reference [.gc_common_config, script]
    - !reference [.gc_define_version, script]
    - !reference [.gc_set_image_name, script]
    - >
      helm upgrade $GC_HELM_DEPLOYMENT_SERVICE oci://$CI_REGISTRY_IMAGE/gc-helm/gc-$GC_SERVICE-deploy
      --version $VERSION
      --install
      --create-namespace
      --namespace=$GC_HELM_NAMESPACE
      --wait
      --history-max=3
      --set data.imagePullPolicy=Always
      --set data.serviceAccountName=$SEISMIC_GC_SERVICE
      --set data.appEnvironmentIdentifier=$DATA_PARTITION_ID
      --set data.serviceCloudProject=$GC_PROJECT
      --set global.domain=$GC_DOMAIN
      $GC_HELM_SETS
      $GC_HELM_TIMEOUT
    - !reference [.gc_verify_deploy, script]
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG && $GC == '1'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-' && $GC == '1'
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $GC == '1'
      when: never
