filemetadata_containerize:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags: ['osdu-medium']
  stage: containerize
  needs:
    - filemetadata_unit_test
  variables:
    SHA_IMAGE: ${FILEMETADATA_LOCAL_SERVICE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    LATEST_IMAGE: ${FILEMETADATA_LOCAL_SERVICE_NAME}:latest
  before_script:
    - cd app/$FILEMETADATA_SERVICE
    - sed -i "s/SEGY_LIBRARY_PAT/$SEGY_LIBRARY_FEED_PAT/g" pip.conf
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $FILEMETADATA_LOCAL_SERVICE_NAME --file Dockerfile .
    - docker tag $FILEMETADATA_LOCAL_SERVICE_NAME $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker tag $FILEMETADATA_LOCAL_SERVICE_NAME $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$LATEST_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - devops/**/*
        - app/filemetadata/**/*
      when: always
