<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../test.common.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.12.0" />
        <PackageReference Include="Moq" Version="4.18.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Sidecar.Common\Sidecar.Common.csproj" />
        <ProjectReference Include="..\..\src\Sidecar.RestoreRunner\Sidecar.RestoreRunner.csproj" />
    </ItemGroup>

</Project>
