filemetadata_prepare_fossa:
  image: python
  stage: build
  before_script:
    - cd app/$FILEMETADATA_SERVICE
  script:
    - export PIP_CONFIG_FILE=${PWD}/pip.conf
    - cd app
    - pip install -r requirements.txt
    - pip freeze > ../../../all-requirements.txt
  artifacts:
    paths:
      - all-requirements.txt
    expire_in: 15 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      when: always
    - if: $CI_COMMIT_BRANCH =~ '/^trusted-'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - devops/**/*
        - app/filemetadata/**/*
      when: always
