#!/bin/bash
#  ***************************************************************************
#  Copyright 2017 - 2023, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************


printf "\n%s\n" "-------------------------------------------------------"
echo "validate commit message sdms"
printf "%s\n" "-------------------------------------------------------"

mex=$(cat $1)
REGEX="^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)"
if [[ ! "$mex" =~ $REGEX ]]; then
    printf "%s\n" "ERROR: the commit message need to follow the conventional commits syntax"
    printf "%s\n" "https://github.com/conventional-changelog/commitlint/#what-is-commitlint"
    exit 1
else
    printf "%s\n" "commit message compliant with commitlint syntax"
fi
