#!/usr/bin/env sh
#  ***************************************************************************
#  Copyright 2017 - 2023, Schlumberger
#
#  Licensed under the Apache License, Version 2.0(the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ***************************************************************************

. "$(dirname -- "$0")/_/husky.sh"

cd ./app/sdms-v4 

if [ ! -d "node_modules" ]
then
    echo "error: required modules not found, please run \"npm\" install before commit"
    exit 1
fi

printf "\n%s\n" "-------------------------------------------------------"
echo "1 - spelling errors check"
printf "%s\n" "-------------------------------------------------------"
npm run spell

printf "\n%s\n" "-------------------------------------------------------"
echo "2 - markdown linting"
printf "%s\n" "-------------------------------------------------------"
npm run markdown-lint

printf "\n%s\n" "-------------------------------------------------------"
echo "3 - code linting"
printf "%s\n" "-------------------------------------------------------"
npm run lint

printf "%s\n" "-------------------------------------------------------"
echo "4 - code formatting"
printf "%s\n" "-------------------------------------------------------"
npm run prettier
