#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
rootPath=$(git rev-parse --show-toplevel)
cd "$rootPath"
echo "-------------------------------------------------------"
echo "1)"
echo "Install modules required"
npm install -g cspell
npm install -g markdownlint-cli
npm install -g scan-for-secrets
echo "-------------------------------------------------------"
echo "2)"
echo "Scans for secrets"
for f in $(git diff --cached --name-only --diff-filter=ACM); do
  if [ -d $f ]; then
    echo "Scanning $f"
    npx scan-for-secrets $f
  else
    dir="$(dirname "${f}")"
    if [ "$dir" == *"app/sdms" ]; then
      echo "Scanning $f"
      npx scan-for-secrets ${dir}/src
    fi
  fi
done
echo "-------------------------------------------------------"
echo "3)"
echo "CSpell scan"
for f in $(git diff --cached --name-only --diff-filter=ACM); do
  if [[ ! "$f" == *"package.json"* && ! "$f" == *"package-lock.json"* && ! "$f" == *"npm-shrinkwrap.json"* && ! "$f" == *"markdownlint.json"* && ! "$f" == *"cspell.json"* ]]; then
    echo "Scanning $f"
    npx cspell $f --gitignore --show-suggestions
  fi
done
echo "-------------------------------------------------------"
echo "4)"
echo "Markdown lint"
for f in $(git diff --cached --name-only --diff-filter=ACM); do
  if [ "$f" == *".md"* ]; then
    echo "Markdown linting $f"
    npx markdownlint $f
  fi
done
echo "-------------------------------------------------------"
echo "5)"
echo "lint & test .NET if necessary"
dotnet_changed=$(
  git diff --name-only --cached |  # only check the files that will be committed
  grep "app/sdms/src/cloud/providers/azure/sidecar/.*.cs" |  # select only the C# files
  head -n 1
)
if [ ! -z "$dotnet_changed" ]
then
  cd app/sdms/src/cloud/providers/azure/sidecar/
  dotnet format --severity warn --verify-no-changes
  dotnet test
  cd ../../../../../../..
fi
echo "-------------------------------------------------------"

