{{- template "common.serviceaccount" (list . "os-seismic-ddms-v4.serviceaccount") -}}
{{- define "os-seismic-ddms-v4.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}