sdms_v4_markdownlint:
  image: node
  tags: ["osdu-small"]
  stage: scan
  needs: ['sdms_v4_push_runtime_image']
  allow_failure: true
  script:
    - cd app/$SDMS_V4_SERVICE
    - npm install -g typescript
    - npm install -g markdownlint-cli
    - markdownlint "**/*.md" > ../../markdownlint_report.txt
  artifacts:
    paths:
      - markdownlint_report.txt
    when: always
    expire_in: 2 days
  only:
    changes:
      - devops/**/*
      - app/sdms-v4/**/*
    refs:
      - branches
      - merge_requests
