sdms_v4_scan-for-secrets:
  image: python
  tags: ["osdu-small"]
  stage: scan
  needs: []
  script:
    - pip install detect-secrets
    - cd app/$SDMS_V4_SERVICE
    - detect-secrets-hook --exclude-files package-lock.json --exclude-files package.json --exclude-files tests/e2e/models/FileCollection.Slb.OpenZGY.1.0.0.json --exclude-files tests/e2e/models/FileCollection.SEGY.1.0.0.json --exclude-files tests/e2e/models/FileCollection.Generic.1.0.0.json --exclude-files tests/e2e/models/FileCollection.Bluware.OpenVDS.1.0.0.json --exclude-files tests/auth/models/FileCollection.Generic.1.0.0.json --exclude-files devops/osdu/scanners/scan-for-secrets-node.yml --baseline devops/config/detect_secrets/.secrets.baseline $(git ls-files)
  only:
    changes:
      - devops/**/*
      - app/sdms-v4/**/*
    refs:
      - branches
      - merge_requests
