.filemetadata_prepare_fossa:
  before_script:
    - cp -Rf app/${FILEMETADATA_SERVICE}/*.* .
    - cp -Rf app/${FILEMETADATA_SERVICE}/* .
    - cp -Rf app/${FILEMETADATA_SERVICE}/. .
    - cp -Rf app/${FILEMETADATA_SERVICE}/.fossa.yml .
    - rm -Rf app/sdms
    - rm -Rf app/sdms-v4
    - rm -Rf app/${FILEMETADATA_SERVICE}/*.*
    - rm -Rf app/${FILEMETADATA_SERVICE}/*
    - sed -i "s/SEGY_LIBRARY_PAT/$SEGY_LIBRARY_FEED_PAT/g" pip.conf
    - export PIP_CONFIG_FILE="${PWD}/pip.conf"
    - pip install -r app/requirements.txt
    - pip freeze > all-requirements.txt
    - cp all-requirements.txt app/.

.filemetadata_prepare_fossa_check_notice:
  before_script:
    - mkdir -p app/${FILEMETADATA_SERVICE}/fossa-output
    - cp -Rf fossa-output/. app/${FILEMETADATA_SERVICE}/fossa-output/.

filemetadata_fossa-analyze:
  extends:
    - .filemetadata_prepare_fossa
    - fossa-analyze
  allow_failure: true
  variables:
    ALLOW_FOSSA_CACHE: 'false'
    FOSSA_OUTPUT_DIR: "app/${FILEMETADATA_SERVICE}/fossa-output"
  needs: 
    - 'filemetadata_containerize'
    - 'filemetadata_prepare_fossa'
  tags: ['osdu-medium']
  script:
    # fossa-with-cache needs a CI_COMMIT_BRANCH defined to know how to parse the FOSSA API results
    # When building tags, this isn't defined by GitLab. In that case, we use the tag name instead. If that's not defined
    # then things will fail and we'll have to make this smarter
    - test -z "$CI_COMMIT_BRANCH" && export CI_COMMIT_BRANCH="$CI_COMMIT_TAG"
    - |
      if [ ! -e all-requirements.txt ]; then
        echo "I was expecting a file named 'all-requirements.txt' to have been generated by compile-and-unit-test"
        echo "However, that file doesn't seem to exist"
        echo "----------------------------------------"
        echo "That file should have been the output of a 'pip freeze', so that I knew what the full list of deep"
        echo "dependencies were. I can't reasonably generate that in this job, because I don't know what python image"
        echo "is appropriate. If this structure has been changed in the build/python.yml, you may need to update this"
        echo "logic as well (in scanners/fossa-python.yml)"
        exit 1
      fi
    # This variable is used by the python build environment to refer to the set of requirements that need to
    # be compiled down into the single 'all-requirements.txt'. Here, we override it to supply fossa-with-cache
    # with a direct answer.
    - PIP_REQUIREMENTS=all-requirements.txt fossa-with-cache
  artifacts:
    paths:
      - app/${FILEMETADATA_SERVICE}/fossa-output
    when: always
    expire_in: 2 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_TAG && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ 'trusted-.+' && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_REF_PROTECTED && $FOSSA_API_KEY
      changes:
        - app/filemetadata/**/*
      when: on_success
    - if: $FOSSA_API_KEY
      changes:
        - app/filemetadata/**/*
      when: on_success

filemetadata_fossa-check-notice:
  extends:
    - .filemetadata_prepare_fossa
    - .filemetadata_prepare_fossa_check_notice
    - fossa-check-notice
  allow_failure: true
  needs: ['filemetadata_fossa-analyze']
  tags: ['osdu-medium']
  before_script:
    - !reference [.filemetadata_prepare_fossa, before_script]
    - !reference [.filemetadata_prepare_fossa_check_notice, before_script]
  artifacts:
    when: on_failure
    paths:
      - app/${FILEMETADATA_SERVICE}/fossa-output/cached-NOTICE
      - app/${FILEMETADATA_SERVICE}/fossa-output/generated-clean-NOTICE
    expire_in: 2 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_TAG && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ 'trusted-.+' && $FOSSA_API_KEY
      when: on_success
    - if: $CI_COMMIT_REF_PROTECTED && $FOSSA_API_KEY
      changes:
        - app/filemetadata/**/*
      when: on_success
    - if: $FOSSA_API_KEY
      changes:
        - app/filemetadata/**/*
      when: on_success

fossa-analyze:
  needs: []
  rules:
    - if: $DISABLED == 'true'
      when: never

fossa-check-notice:
  rules:
    - if: $DISABLED == 'true'
      when: never