filemetadata_scan-for-secrets:
  image: python
  tags: ["osdu-small"]
  stage: scan
  needs: []
  script:
    - pip install detect-secrets
    - cd app/$FILEMETADATA_SERVICE
    - detect-secrets-hook --exclude-files devops/osdu/scanners/scan-for-secrets-node.yml --baseline devops/config/detect_secrets/.secrets.baseline $(git ls-files)
  only:
    changes:
      - devops/**/*
      - app/filemetadata/**/*
    refs:
      - branches
      - merge_requests
