aws-containerize:
  needs: []
  only:
    variables:
      - $DISABLED == 'true'

aws-update-helm:
  only:
    variables:
      - $DISABLED == 'true'

aws-update-tf:
  rules:
    - if: $DISABLED == 'true'
      when: never

aws-update-eks:
  only:
    variables:
      - $DISABLED == 'true'