core-deploy:
  rules:
    - if: $DISABLED == 'true'
      when: never

core-test:
  extends:
    - .gc-variables
  rules:
    - if: $DISABLED == 'true'
      when: never

core-acceptance-test:
  rules:
    - if: $DISABLED == 'true'
      when: never

core-test-python:
  rules:
    - if: $DISABLED == 'true'
      when: never
