gc-baremetal-deploy:
  rules:
    - if: $DISABLED == 'true'
      when: never

gc-baremetal-test:
  extends:
    - .gc-baremetal-variables
  rules:
    - if: $DISABLED == 'true'
      when: never

gc-baremetal-osdutest:
  rules:
    - if: $DISABLED == 'true'
      when: never

gc-baremetal-test-python:
  rules:
    - if: $DISABLED == 'true'
      when: never
