include:
  - local: devops/osdu/cloud-providers/gc-com-gke.yml
  - local: devops/osdu/cloud-providers/gc-containerize.yml
  - local: devops/osdu/cloud-providers/gc-dev2-gke.yml
  - local: devops/osdu/cloud-providers/gc-helm.yml
  - local: devops/osdu/cloud-providers/gc-preship-gke.yml

variables:
  GC_GCR_REGISTRY: "gcr.io/osdu-anthos"
  APP_VERSION: "$GC_HELM_PACKAGE_VERSION-SNAPSHOT"
