gc-helm-charts-gitlab:
  rules:
    - if: $DISABLED == 'true'
      when: never

gc-helm-charts-release-gitlab:
  rules:
    - if: $DISABLED == 'true'
      when: never

gc-helm-charts-release-gcr:
  rules:
    - if: $DISABLED == 'true'
      when: never
